import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'hi' | 'gu' | 'en';

const translations = {
  hi: {
    appName: 'किसान बाज़ार',
    home: 'होम',
    login: 'लॉगिन',
    signup: 'साइन अप',
    farmer: 'किसान',
    trader: 'व्यापारी',
    name: 'नाम',
    village: 'गाँव',
    mobile: 'मोबाइल नंबर',
    crops: 'फसलें',
    businessName: 'व्यापार का नाम',
    location: 'स्थान',
    sendOtp: 'OTP भेजें',
    enterOtp: 'OTP दर्ज करें',
    verifyOtp: 'OTP सत्यापित करें',
    otpSent: 'OTP भेजा गया!',
    otpSentTo: 'OTP भेजा गया',
    enterValidMobile: 'सही मोबाइल नंबर दर्ज करें',
    enterValidOtp: 'सही 6-अंकों का OTP दर्ज करें',
    changeNumber: 'नंबर बदलें',
    fillAllFields: 'सभी फ़ील्ड भरें',
    back: 'वापस',
    call: 'कॉल करें',
    whatsapp: 'व्हाट्सएप',
    search: 'खोजें...',
    filterByCrop: 'फसल से खोजें',
    filterByLocation: 'स्थान से खोजें',
    bestPrice: 'सबसे अच्छी कीमत',
    rating: 'रेटिंग',
    trustedTrader: 'विश्वसनीय व्यापारी',
    deals: 'सफल सौदे',
    perKg: '₹/20किलो',
    addCrop: 'फसल जोड़ें',
    setPrice: 'कीमत सेट करें',
    dashboard: 'डैशबोर्ड',
    myCrops: 'मेरी फसलें',
    editPrice: 'कीमत बदलें',
    save: 'सेव करें',
    cancel: 'रद्द करें',
    giveFeedback: 'प्रतिक्रिया दें',
    writeReview: 'समीक्षा लिखें...',
    submit: 'जमा करें',
    reviews: 'समीक्षाएं',
    allCrops: 'सभी फसलें',
    loginAs: 'के रूप में लॉगिन करें',
    signupAs: 'के रूप में साइन अप',
    noAccount: 'खाता नहीं है?',
    hasAccount: 'पहले से खाता है?',
    topTraders: 'शीर्ष व्यापारी',
    nearYou: 'आपके पास',
    welcome: 'स्वागत है',
    logout: 'लॉगआउट',
    cropName: 'फसल का नाम',
    price: 'कीमत (₹/20किलो)',
    delete: 'हटाएं',
    edit: 'बदलें',
    subscription: 'सदस्यता',
    free: 'मुफ्त',
    selectCrops: 'फसलें चुनें',
    email: 'ईमेल',
    loading: 'लोड हो रहा है...',
    signupFirst: 'पहले साइन अप करें, फिर लॉगिन करें',
    loginRequired: 'यह करने के लिए पहले लॉगिन करें',
    loginToReview: 'समीक्षा देने के लिए लॉगिन करें',
    noReviewsYet: 'अभी तक कोई समीक्षा नहीं है',
    reviewSubmitted: 'समीक्षा जमा हो गई!',
    reviewSubmitFailed: 'समीक्षा जमा नहीं हो सकी',
    cropAdded: 'फसल जोड़ दी गई!',
    cropDeleted: 'फसल हटा दी गई!',
    priceUpdated: 'कीमत अपडेट हो गई!',
    noTradersFound: 'कोई व्यापारी नहीं मिला',
    loginFailed: 'लॉगिन नहीं हो सका',
    signupFailed: 'साइन अप नहीं हो सका',
    devOtpMode: 'डेवलपमेंट OTP मोड सक्रिय है',
    devOtpHint: 'प्रिव्यू में टेस्ट OTP: 123456',
  },
  gu: {
    appName: 'ખેડૂત બજાર',
    home: 'હોમ',
    login: 'લૉગિન',
    signup: 'સાઇન અપ',
    farmer: 'ખેડૂત',
    trader: 'વેપારી',
    name: 'નામ',
    village: 'ગામ',
    mobile: 'મોબાઈલ નંબર',
    crops: 'પાક',
    businessName: 'વેપારનું નામ',
    location: 'સ્થાન',
    sendOtp: 'OTP મોકલો',
    enterOtp: 'OTP દાખલ કરો',
    verifyOtp: 'OTP ચકાસો',
    otpSent: 'OTP મોકલ્યો!',
    otpSentTo: 'OTP મોકલ્યો',
    enterValidMobile: 'સાચો મોબાઈલ નંબર દાખલ કરો',
    enterValidOtp: 'સાચો 6-અંકનો OTP દાખલ કરો',
    changeNumber: 'નંબર બદલો',
    fillAllFields: 'બધા ફીલ્ડ ભરો',
    back: 'પાછા',
    call: 'કૉલ કરો',
    whatsapp: 'વૉટ્સએપ',
    search: 'શોધો...',
    filterByCrop: 'પાક દ્વારા શોધો',
    filterByLocation: 'સ્થાન દ્વારા શોધો',
    bestPrice: 'શ્રેષ્ઠ કિંમત',
    rating: 'રેટિંગ',
    trustedTrader: 'વિશ્વાસુ વેપારી',
    deals: 'સફળ સોદા',
    perKg: '₹/20કિલો',
    addCrop: 'પાક ઉમેરો',
    setPrice: 'કિંમત સેટ કરો',
    dashboard: 'ડેશબોર્ડ',
    myCrops: 'મારા પાક',
    editPrice: 'કિંમત બદલો',
    save: 'સેવ કરો',
    cancel: 'રદ કરો',
    giveFeedback: 'પ્રતિક્રિયા આપો',
    writeReview: 'સમીક્ષા લખો...',
    submit: 'સબમિટ કરો',
    reviews: 'સમીક્ષાઓ',
    allCrops: 'બધા પાક',
    loginAs: 'તરીકે લૉગિન કરો',
    signupAs: 'તરીકે સાઇન અપ',
    noAccount: 'ખાતું નથી?',
    hasAccount: 'પહેલેથી ખાતું છે?',
    topTraders: 'ટોચના વેપારીઓ',
    nearYou: 'તમારી નજીક',
    welcome: 'સ્વાગત છે',
    logout: 'લૉગઆઉટ',
    cropName: 'પાકનું નામ',
    price: 'કિંમત (₹/20કિલો)',
    delete: 'કાઢી નાખો',
    edit: 'બદલો',
    subscription: 'સબ્સ્ક્રિપ્શન',
    free: 'મફત',
    selectCrops: 'પાક પસંદ કરો',
    email: 'ઇમેઇલ',
    loading: 'લોડ થઈ રહ્યું છે...',
    signupFirst: 'પહેલા સાઇન અપ કરો, પછી લૉગિન કરો',
    loginRequired: 'આ કરવા માટે પહેલા લૉગિન કરો',
    loginToReview: 'સમીક્ષા આપવા માટે લૉગિન કરો',
    noReviewsYet: 'હજુ સુધી કોઈ સમીક્ષા નથી',
    reviewSubmitted: 'સમીક્ષા મોકલી દેવામાં આવી!',
    reviewSubmitFailed: 'સમીક્ષા મોકલી શકાયી નહીં',
    cropAdded: 'પાક ઉમેરાઈ ગયો!',
    cropDeleted: 'પાક કાઢી નાખ્યો!',
    priceUpdated: 'કિંમત સુધારી દેવામાં આવી!',
    noTradersFound: 'કોઈ વેપારી મળ્યો નથી',
    loginFailed: 'લૉગિન નિષ્ફળ ગયું',
    signupFailed: 'સાઇન અપ નિષ્ફળ ગયું',
    devOtpMode: 'ડેવલપમેન્ટ OTP મોડ સક્રિય છે',
    devOtpHint: 'પ્રિવ્યૂ માટે ટેસ્ટ OTP: 123456',
  },
  en: {
    appName: 'Kisan Bazaar',
    home: 'Home',
    login: 'Login',
    signup: 'Sign Up',
    farmer: 'Farmer',
    trader: 'Trader',
    name: 'Name',
    village: 'Village',
    mobile: 'Mobile Number',
    crops: 'Crops',
    businessName: 'Business Name',
    location: 'Location',
    sendOtp: 'Send OTP',
    enterOtp: 'Enter OTP',
    verifyOtp: 'Verify OTP',
    otpSent: 'OTP sent!',
    otpSentTo: 'OTP sent to',
    enterValidMobile: 'Enter a valid mobile number',
    enterValidOtp: 'Enter a valid 6-digit OTP',
    changeNumber: 'Change Number',
    fillAllFields: 'Fill all fields',
    back: 'Back',
    call: 'Call',
    whatsapp: 'WhatsApp',
    search: 'Search...',
    filterByCrop: 'Filter by Crop',
    filterByLocation: 'Filter by Location',
    bestPrice: 'Best Price',
    rating: 'Rating',
    trustedTrader: 'Trusted Trader',
    deals: 'Successful Deals',
    perKg: '₹/20kg',
    addCrop: 'Add Crop',
    setPrice: 'Set Price',
    dashboard: 'Dashboard',
    myCrops: 'My Crops',
    editPrice: 'Edit Price',
    save: 'Save',
    cancel: 'Cancel',
    giveFeedback: 'Give Feedback',
    writeReview: 'Write review...',
    submit: 'Submit',
    reviews: 'Reviews',
    allCrops: 'All Crops',
    loginAs: 'Login as',
    signupAs: 'Sign up as',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    topTraders: 'Top Traders',
    nearYou: 'Near You',
    welcome: 'Welcome',
    logout: 'Logout',
    cropName: 'Crop Name',
    price: 'Price (₹/20kg)',
    delete: 'Delete',
    edit: 'Edit',
    subscription: 'Subscription',
    free: 'Free',
    selectCrops: 'Select Crops',
    email: 'Email',
    loading: 'Loading...',
    signupFirst: 'Please sign up first, then log in',
    loginRequired: 'Please log in first to continue',
    loginToReview: 'Log in to leave a review',
    noReviewsYet: 'No reviews yet',
    reviewSubmitted: 'Review submitted!',
    reviewSubmitFailed: 'Failed to submit review',
    cropAdded: 'Crop added!',
    cropDeleted: 'Crop deleted!',
    priceUpdated: 'Price updated!',
    noTradersFound: 'No traders found right now',
    loginFailed: 'Login failed',
    signupFailed: 'Signup failed',
    devOtpMode: 'Development OTP mode enabled',
    devOtpHint: 'Preview test OTP: 123456',
  },
};

type TranslationKey = keyof typeof translations.en;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('hi');

  const t = (key: TranslationKey): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
